name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bulid projrct
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run tests
      run: ctest

